# SPDX-License-Identifier: GPL-2.0-or-later
#
#  Copyright (C) 2023 Xilinx Inc.
#

PACKAGE_NAME=amd-ama-kmod
PACKAGE_VERSION=1.5.0

DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"

MAKE="KERNEL_VERSION=${kernelver} OSAL_INCLUDE=-I. ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/build_driver.sh"
CLEAN="${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/build_driver.sh clean"

BUILT_MODULE_NAME="ama_transcoder"
BUILT_MODULE_LOCATION="."
AUTOINSTALL=yes
BUILD_EXCLUSIVE_KERNEL="^(5\.1[4-9]+\.|6\.[0-9]+\.)"
